<a href="https://colab.research.google.com/github/aryadeo/python_basics/blob/master/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Date: 18_10_2019
Here we are going to learn about some basic commands to be used in numpy.

In [0]:
import numpy as np

#creating an array

In [62]:
a_1=np.array([1,2,3])
a_2=np.array([((1,2,3),(4,5,6),(7,8))])
print('array is:',a_1,'and its dimension is',np.ndim(a_1))
print('array is:',a_2,'and its dimension is',np.ndim(a_2))

array is: [1 2 3] and its dimension is 1
array is: [[(1, 2, 3) (4, 5, 6) (7, 8)]] and its dimension is 2


#Null Array
It is possible to create a null array of 1D and 2D dimension only. By opting to create null array of higher dimension, it takes it as 2D only. A higher dimesion array will be created only if youe are giving some input.

In [54]:
#creating a null array
a_null=np.array([])
print('created null array is a_null=',a_null)
a_null_1=np.array([(((((())))))])
print('created null array is a_null_1=',a_null_1)
print(np.ndim(a_null_1))

created null array is a_null= []
created null array is a_null_1= []
2


Using the command "numpy.empty([p,q])"you can create a null array with uninitialized random values filled in as default. Of course, you can reinitialize the values.

In [0]:
a_null_2=np.empty([2,2,2,2]) #uninitialized and output may vary
a_null_2

#nD array
tensor dimension depend on the number of paranthesis you have entered. Let's see the below examples.


In [52]:
a_3=np.array([])
print('dimension of the array a_3 is:',np.ndim(a_3))

a_4=np.array([()])
print('dimension of the array a_4 is:',np.ndim(a_4))

a_5=np.array([((()))])      #only giving paranthersis does not increases array dimension.
print('dimension of the array a_5 is:',np.ndim(a_5))

a_6=np.array([(((1,2),(3,4,5),(8,3,1,4)))])
print('dimension of the array a_6 is:',np.ndim(a_6))

a_7=np.array([((((1,2,3),(4,5,6))))])     #this is an array of sequence of sequence of sequences.
print('dimension of the array a_7 is:',np.ndim(a_7))

a_8=np.array([((((1,2),(2,3)),((3,2),(2,3))),((4,5),(6,7)))])
print('dimension of the array a_8 is:',np.ndim(a_8))

dimension of the array a_3 is: 1
dimension of the array a_4 is: 2
dimension of the array a_5 is: 2
dimension of the array a_6 is: 2
dimension of the array a_7 is: 3
dimension of the array a_8 is: 4


In [24]:
a_test=np.arange(16)
print('created array is:',a_test)
a_test_1=np.reshape(a_test,(2,2,1))
print("reshaped array is",a_test_1)
print(np.ndim(a_test_1))

created array is: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
reshaped array is [[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
4
