<a href="https://colab.research.google.com/github/aryadeo/python_basics/blob/master/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Date: 18_10_2019
Here we are going to learn about some basic commands to be used in numpy.

In [0]:
import numpy as np

#creating an array
Numpy array has a fixed length unlike the list datatype. Changing the length of an array will delete the old one and create a new one. But it won't allow to chage the length dynamicaally, as is the case in list,

In [0]:
a_1=np.array([1,2,3])
a_2=np.array([((1,2,3),(4,5,6),(7,8))])
print('array is:',a_1,'and its dimension is',np.ndim(a_1))
print('array is:',a_2,'and its dimension is',np.ndim(a_2))

In [0]:
a_test_1=np.array([2,3,4,5],dtype=int)
a_test_2=np.array([2,3,4,5],dtype=float)
a_test_3=np.array([2,3,4,5],dtype=complex)
print(a_test_1)
print(a_test_2)
print(a_test_3)

In [0]:
a_test_4=np.zeros((2,3))
print(a_test_4)

In [0]:
a_test_5=np.ones((5,5))
print(a_test_5)

In [0]:
a_test_6=np.arange(20)
print(a_test_6)

In [0]:
#reshaping
a_test_7=np.reshape(a_test_6,(2,10))
print(a_test_7)

In [0]:
a_test_8=np.arange(5,9,0.3,dtype=float)
print(a_test_8)

due to precision probem, using arange command in float type array create problem. So its preferable to use linspace

In [0]:
a_test_9=np.linspace(5,9,10,dtype=float)
print(a_test_9)

#Null Array
It is possible to create a null array of 1D and 2D dimension only. By opting to create null array of higher dimension, it takes it as 2D only. A higher dimesion array will be created only if youe are giving some input.

In [0]:
#creating a null array
a_null=np.array([])
print('created null array is a_null=',a_null)
a_null_1=np.array([(((((())))))])
print('created null array is a_null_1=',a_null_1)
print(np.ndim(a_null_1))

Using the command "numpy.empty([p,q])"you can create a null array with uninitialized random values filled in as default. Of course, you can reinitialize the values.

In [0]:
a_null_2=np.empty([2,2,2,2]) #uninitialized and output may vary
a_null_2

#nD array
tensor dimension depend on the number of paranthesis you have entered. Let's see the below examples.


In [0]:
a_3=np.array([])
print('dimension of the array a_3 is:',np.ndim(a_3))

a_4=np.array([()])
print('dimension of the array a_4 is:',np.ndim(a_4))

a_5=np.array([((()))])      #only giving paranthersis does not increases array dimension.
print('dimension of the array a_5 is:',np.ndim(a_5))

a_6=np.array([(((1,2),(3,4,5),(8,3,1,4)))])
print('dimension of the array a_6 is:',np.ndim(a_6))

a_7=np.array([((((1,2,3),(4,5,6))))])     #this is an array of sequence of sequence of sequences.
print('dimension of the array a_7 is:',np.ndim(a_7))

a_8=np.array([((((1,2),(2,3)),((3,2),(2,3))),((4,5),(6,7)))])
print('dimension of the array a_8 is:',np.ndim(a_8))

In [0]:
a_test=np.arange(16)
print('created array is:',a_test)
a_test_1=np.reshape(a_test,(2,2,1))
print("reshaped array is",a_test_1)
print(np.ndim(a_test_1))

date: 21st october, 2019

In [0]:
a_test_10=np.array([(2,3,5),(4,5,6)])
print(a_test_10)
print(np.shape(a_test_10))
print(np.ndim(a_test_10))

[[2 3 5]
 [4 5 6]]
(2, 3)
2


In [0]:
#converting from list to array
a_test_11=[1,2,3]
a_test_12=np.asarray(a_test_11,float)
print('created list is:',a_test_11,'and its type is:',type(a_test_11))
print('converted array is:',a_test_12,'and its type is:',type(a_test_12))

created list is: [1, 2, 3] and its type is: <class 'list'>
converted array is: [1. 2. 3.] and its type is: <class 'numpy.ndarray'>


In [0]:
#transpose of an array
a_test_13=np.random.random((2,3))
print(a_test_13)
print("transpose is:",a_test_13.T)#procedure to write the transpose

[[0.07102627 0.20596904 0.41549543]
 [0.79017582 0.59755846 0.03318607]]
transpose is: [[0.07102627 0.79017582]
 [0.20596904 0.59755846]
 [0.41549543 0.03318607]]


In [0]:
#floor values
a_test_14=np.floor((np.random.random((2,3)))*10)
print(a_test_14)

[[1. 3. 4.]
 [6. 2. 4.]]


Inner and Outer product
![basic explanation](https://drive.google.com/uc?id=1Kv59N9xlkG2PswdPoCE1F3iWtdQdhxea)


In [0]:
#inner and outer product
a_test_15=np.array([(2,3,5),(4,5,6)])
a_test_16=np.array([(1,2,3),(4,5,6)])
print(np.inner(a_test_15,a_test_16))
#this product is element wise multiplication. in this type of product each element is multiplied with each element. 
#In this case (2,3,5) is multiplied with (1,2,3) first and then (2,3,5) is multiplied with(4,5,6). in the next term
#(4,5,6) is multiplied with (1,2,3) and then (4,5,6) is multiplied with (4,5,6).

#outer product
print('outer product is:',np.outer(a_test_15,a_test_16))
#here 2 is multiplied with every element of the other array i.e. 2*1,2*2,2*3,2*4,2*5,2*6
#and it is repeated for every other element in the first array.

[[23 53]
 [32 77]]
outer product is: [[ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 5 10 15 20 25 30]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [28]:
#dot product
print('the dot product of the previous two matrices is:',np.dot(a_test_15,a_test_16))
#its creating an error duee to shape mismatch. let's rectify it

ValueError: ignored

In [34]:
a_test_17=np.ones((2,3))
a_test_18=np.ones((3,2))
print('the dot product of the previous two matrices is:',np.dot(a_test_17,a_test_18))

the dot product of the previous two matrices is: [[3. 3.]
 [3. 3.]]


In [41]:
#getting sum
print(a_test_17)
print(a_test_17.sum())#addition of each element as a scalar
print(a_test_17.sum(axis=0))#raddition of every column
print(a_test_17.sum(axis=1))#addition of every row
print(a_test_17.max())#the max value among each element

[[1. 1. 1.]
 [1. 1. 1.]]
6.0
[2. 2. 2.]
[3. 3.]
1.0
